### ISSUE TITLE
Add view helper class, that separates all children from each other

### ISSUE THREAD

**Issue by apfelbox** [Becklyn/GluggiBundle#10]
This is useful if I want to list all variants of a single component.

Something along the lines of 
```css
.gluggi-previews * + *{
    margin-top: 30px;
}
```
